name: Terraform Backend Bootstrap (S3)

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Terraform bootstrap directory (e.g. terraform/bootstrap/s3)"
        required: true
        default: terraform/bootstrap/s3

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ./${{ inputs.working_directory }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ./${{ inputs.working_directory }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./${{ inputs.working_directory }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./${{ inputs.working_directory }}
        run: terraform apply -auto-approve
