name: Terraform Apply (Prod firewall)

on:
  workflow_dispatch:
    inputs:
      working_directory:
       description: "Terraform working directory"
       required: true

      aws_access_key:
        description: "AWS Access Key"
        required: true

      aws_secret_key:
        description: "AWS Secret Key"
        required: true

      aws_region:
        description: "AWS Region"
        required: true

      instance_type:
        description: "EC2 instance type"
        required: true

      root_volume_type:
        description: "Root volume type"
        required: true

      root_volume_size:
        description: "Root volume size (GB)"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Apply
        working-directory: ./terraform/envs/${{ inputs.working_directory }}
        env:
          TF_VAR_aws_access_key: ${{ inputs.aws_access_key }}
          TF_VAR_aws_secret_key: ${{ inputs.aws_secret_key }}
          TF_VAR_aws_region: ${{ inputs.aws_region }}

          TF_VAR_environment: ${{ inputs.working_directory }}
          TF_VAR_instance_type: ${{ inputs.instance_type }}
          TF_VAR_root_volume_type: ${{ inputs.root_volume_type }}
          TF_VAR_root_volume_size: "${{ inputs.root_volume_size }}"
          TF_VAR_delete_on_termination: "${{ vars.DELETE_ON_TERMINATION }}"               #vars ho hai

          TF_VAR_ami_owners: '["${{ vars.AMI_OWNERS }}"]'                                 #vars ho hai
          TF_VAR_ami_name_pattern: ${{ vars.AMI_NAME_PATTERN }}                           #vars ho hai   
          TF_VAR_ami_virtualization_type: ${{ vars.AMI_VIRTUALIZATION_TYPE }}             #vars ho hai
          TF_VAR_ami_architecture: ${{ vars.AMI_ARCHITECTURE }}                           #vars ho hai

          TF_VAR_tags: '{"Project":"ec2","Environment":"${{ inputs.working_directory }}","ManagedBy":"terraform","Owner":"Security-Team"}'

        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
